### PR TITLE
add support for LNS3.0

### PR DESCRIPTION
**Pull request by sunxuold**
add support for LNS3.0

# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested Locally?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [x] Test B

**Test Configuration**:
* Build OS name and version:
* Docker (Y/N):
* JELOS Branch:
* Any additional information that may be useful:

## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

Note: This PR template is adapted from [embeddedartistry](https://github.com/embeddedartistry/templates/blob/master/oss_docs/PULL_REQUEST_TEMPLATE.md)

### CODE REVIEW

**Comment by fewtarius** [comment]
Please fill out the PR templates, and describe the changes in detail.

**Comment by revjkramer** [comment]
I got to tell you... I prefer ya'll building this instead of me. This takes a long time, even on an M1 mac.

**Comment by sunxuold** [comment]
this patch can support the game  https://openborgames.com/final-fight-lns-3-0-openbor, and i already tested it

**Comment by Rocky5** [comment]
> this patch can support the game https://openborgames.com/final-fight-lns-3-0-openbor, and i already tested it

I gave it a shot and it doesn't work for me. When I load the pak file it its loading is -1 complete then goes to 0 complete and quits back to ES.

**Comment by fewtarius** [comment]
Thanks for testing.  We won't merge this one.

**Pull request closed without merging**
