### PR TITLE
Bluetooth support for RG353P (no settings)

### PR DESCRIPTION
**Pull request by tom-pratt**
Working firmware, bluez and batocera-bluetooth-agent. No UI or settings at this point.

Toggle bluetooth: `systemctl start/stop bluetooth`
Initiate pairing: `batocera-bluetooth trust`

### CODE REVIEW

**Comment by abelsromero** [comment]
It does not seem to be working, at least on RG503.

Connected via ssh and `systemctl list-units --type=service | grep bluetooth` reports the servcie is in "failed", restarting shows it as active for a couple of seconds and logs...

`journalctl -u bluetooth`

```
Nov 12 01:43:25 RG503 bluetoothd[1436]: Starting SDP server
Nov 12 01:43:25 RG503 bluetoothd[1436]: profiles/network/bnep.c:bnep_init() kernel lacks bnep-protocol support
Nov 12 01:43:25 RG503 bluetoothd[1436]: src/plugin.c:plugin_init() System does not support network plugin
Nov 12 01:43:25 RG503 bluetoothd[1436]: Bluetooth management interface 1.14 initialized
```

**Comment by fewtarius** [comment]
It's working fine here.

> It does not seem to be working, at least on RG503.
> 
> Connected via ssh and `systemctl list-units --type=service | grep bluetooth` reports the servcie is in "failed", restarting shows it as active for a couple of seconds and logs...
> 
> `journalctl -u bluetooth`
> 
> ```
> Nov 12 01:43:25 RG503 bluetoothd[1436]: Starting SDP server
> Nov 12 01:43:25 RG503 bluetoothd[1436]: profiles/network/bnep.c:bnep_init() kernel lacks bnep-protocol support
> Nov 12 01:43:25 RG503 bluetoothd[1436]: src/plugin.c:plugin_init() System does not support network plugin
> Nov 12 01:43:25 RG503 bluetoothd[1436]: Bluetooth management interface 1.14 initialized
> ```

Hmm, it's working ok here.

```
RG503:~ # systemctl list-units --type=service | grep bluetooth
  bluetooth-agent.service                loaded active running Start bluetooth agent
  bluetooth-defaults.service             loaded active exited  Bluetooth defaults
  bluetooth.service                      loaded active running Bluetooth service
RG503:~ # grep Hardware /proc/cpuinfo
Hardware	: Anbernic RG503
RG503:~ # grep BUILD_ /etc/os-release
BUILD_ID="36099e4f45f7ec504f69b7d953da6e0ceb46c807"
BUILD_BRANCH="main"
BUILD_DATE="Mon Nov  7 13:05:42 UTC 2022"
```

**Comment by abelsromero** [comment]
Thanks for the response!

Same HW and OS version. I just flashed the card 2 days ago, enable wifi and nothing else.
```
==> Build Date: Mon Nov  7 12:26:27 UTC 2022
==> Version: 20221107

RG503:~ # systemctl list-units --type=service | grep bluetooth
● bluetooth-agent.service                loaded failed failed  Start bluetooth agent
  bluetooth.service                      loaded active running Bluetooth service
RG503:~ # grep Hardware /proc/cpuinfo
Hardware	: Anbernic RG503
RG503:~ # grep BUILD_ /etc/os-release
BUILD_ID="36099e4f45f7ec504f69b7d953da6e0ceb46c807"
BUILD_BRANCH="main"
BUILD_DATE="Mon Nov  7 12:26:27 UTC 2022"
```

I've been looking into the services and this is what I found, not that I can get any conclussion tbh. Any help would be appreciated, as last resort I can reflash the card, but I'd like to find an explanation.

1. Listing all `systemctl list-units --type=service --all | grep bluetooth` shows the defaults as "dead". Unlike yours which is "exited".
```
  bluetooth-agent.service                       loaded    failed   failed  Start bluetooth agent
  bluetooth-defaults.service                    loaded    inactive dead    Bluetooth defaults
  bluetooth.service                             loaded    active   running Bluetooth servic
```

2. `bluetooth-defaults.service` logs shows
```
Nov 12 12:44:10 RG503 systemd[1]: Bluetooth defaults was skipped because of a failed condition check (ConditionPathExists=!/storage/.cache/services/bluez.conf)
```

The file DOES exist, and has read permissions for u, g and o, but has 0 bytes.
But I am ignoring this, seeing the service only copies from `/usr/share/services/bluez.conf` and that has also 0 bytes, doesn't seem the cause of the issue.
Nevertheless is interesing it appears as "dead" and yours as "exited".

3. `bluetooth.service` logs show this error, like something is missing
```
profiles/network/bnep.c:bnep_init() kernel lacks bnep-protocol support
src/plugin.c:plugin_init() System does not support network plugin
```
And `cat /proc/config.gz | gunzip | grep BNEP` reports

```
# CONFIG_BT_BNEP is not set
```
Not sure how relevant this is :man_shrugging: 

4. `bluetooth-agent.service` shows batocera python script failing with `raise Exception("Bluetooth adapter not found")`

```
Nov 12 12:43:18 RG503 systemd[1]: Started Start bluetooth agent.
Nov 12 12:43:21 RG503 batocera-bluetooth-agent[1677]: Traceback (most recent call last):
Nov 12 12:43:21 RG503 batocera-bluetooth-agent[1677]:   File "/usr/bin/batocera-bluetooth-agent", line 389, in do_main_loop
Nov 12 12:43:21 RG503 batocera-bluetooth-agent[1677]:     adapter = bluezutils.find_adapter(dev_id)
Nov 12 12:43:21 RG503 batocera-bluetooth-agent[1677]:   File "/usr/lib/python3.9/bluezutils.py", line 14, in find_adapter
Nov 12 12:43:21 RG503 batocera-bluetooth-agent[1677]:     return find_adapter_in_objects(get_managed_objects(), pattern)
Nov 12 12:43:21 RG503 batocera-bluetooth-agent[1677]:   File "/usr/lib/python3.9/bluezutils.py", line 26, in find_adapter_in_objects
Nov 12 12:43:21 RG503 batocera-bluetooth-agent[1677]:     raise Exception("Bluetooth adapter not found")
Nov 12 12:43:21 RG503 batocera-bluetooth-agent[1677]: Exception: Bluetooth adapter not found
Nov 12 12:43:21 RG503 batocera-bluetooth-agent[1677]: During handling of the above exception, another exception occurred:
Nov 12 12:43:21 RG503 batocera-bluetooth-agent[1677]: Traceback (most recent call last):
Nov 12 12:43:21 RG503 batocera-bluetooth-agent[1677]:   File "/usr/bin/batocera-bluetooth-agent", line 456, in <module>
Nov 12 12:43:21 RG503 batocera-bluetooth-agent[1677]:     do_main_loop(options.dev_id)
Nov 12 12:43:21 RG503 batocera-bluetooth-agent[1677]:   File "/usr/bin/batocera-bluetooth-agent", line 392, in do_main_loop
Nov 12 12:43:21 RG503 batocera-bluetooth-agent[1677]:     adapter = bluezutils.find_adapter(None)
Nov 12 12:43:21 RG503 batocera-bluetooth-agent[1677]:   File "/usr/lib/python3.9/bluezutils.py", line 14, in find_adapter
Nov 12 12:43:21 RG503 batocera-bluetooth-agent[1677]:     return find_adapter_in_objects(get_managed_objects(), pattern)
Nov 12 12:43:21 RG503 batocera-bluetooth-agent[1677]:   File "/usr/lib/python3.9/bluezutils.py", line 26, in find_adapter_in_objects
Nov 12 12:43:21 RG503 batocera-bluetooth-agent[1677]:     raise Exception("Bluetooth adapter not found")
Nov 12 12:43:21 RG503 batocera-bluetooth-agent[1677]: Exception: Bluetooth adapter not found
Nov 12 12:43:21 RG503 systemd[1]: bluetooth-agent.service: Main process exited, code=exited, status=1/FAILURE
Nov 12 12:43:21 RG503 systemd[1]: bluetooth-agent.service: Failed with result 'exit-code'.
```
Again, not sure what to think :man_shrugging: It's a bit of a rabbit hole since the error comes from bluez utils, and I wonder how deep it can go.

5. Now, finally, this PR added this firmware and a service that is not present in my machine, `/usr/bin/rtk_hciattach` is not found anywhere, not even under root path.

https://github.com/JustEnoughLinuxOS/distribution/blob/main/packages/kernel/linux-firmware/rockchip-firmware/system.d/hciattach-realtek.service

I wonder if the released image had some problem with the build or some maybe some extra configurations needs to be added? Something @fewtarius did without thinking about it?

**Comment by fewtarius** [comment]
> 

Since this is a closed PR it might be best to join our discord to discuss.  The device I tested is running the stable branch of JELOS without any changes.

**Comment by abelsromero** [comment]
> be best to join our discord to discuss

Sorry, I try to avoid discord as much as possible but I respect it and so long I don't have to create an account is fine.
Just that I find GH issues are the best to deal with issues, things get organized and recorded for others to consult. But I also understand why those are disable to avoid answering same question by users don't bothering to search.

**Pull request merged**
