### PR TITLE
Mednafen: amd64 and rk3326 support

### PR DESCRIPTION
**Pull request by asoderq**
Bugfixes and support for amd64 and rk3326. By no means perfect, but hopefully to a big degree useful.

Below is my braindump of notes in case someone is interesting in improving on it

# Single mednafen.cfg
I have chosen to have a single mednafen.cfg templated with controls macros. Please stick to single config, the config consists of more than just controls but also general configuration and I would like to avoid maintaining the same parameters in multiple places. That said the templated config file will be expanded on first run, and then not regenerated unless it is deleted. Meaning anyone can afterwards with alt+shift+1 remap it and it will stick. In theory there could be quirks for controls, but wonder if it is worth it. Probably just better to let people remap from the defaults.

# Possible dynamic controller config generation in the future
mednafen does support overlay config files per system, and it could be feasible in the future to dynamically generate controller config with this overriding the default controller config, albeit probably a fair bit work, for e.g. multi controller setups.

# Points that can be improved upon:

- lynx doesn't seem to honor the aspect ratio setting, but always go full screen (maybe mednafen bug).  (tested on rk3326)
-  There are no core specific features implemented for psx, I didn't even look at what is available. Someone could take a peek at this. In general I don't map all core settings, but rely on good defaults together with some setables that shouldn't be active by default.
-  I don't know f the light gun touch screen control mapping for saturn works on other devices than win max2. In general not sure how to handle the touch screens. light guns for no other systems mapped.
- Analog stick support is missing for all but 360 controllers in mednafen_gen_config.sh. Analog sticks and trigger should ideally be added to the profile.d/98-controller. Then mednafen_gen_config.sh could be improved.
-  I could not get mednafens autosave to work, this is atm available in the configuration in ES. Should I remove if I can't get it to work?

Should I rebase on dev before merging?
 
Please let me know any other concerns, though I prefer to change as little as possible as I rather merge in existing support as perfecting mednafen intergration is not a small task imo.

### CODE REVIEW

**Comment by asoderq** [comment]
Ohh and by default the hotkeys should be like in retroarch. There probably should be some documentation written for this as well in the future, but atm I just want to merge what is there not to keep others from improving on it.

I would wait with enabling it for rk3566 until it has mainline and OpenGL.

**Comment by asoderq** [comment]
Rebased, and removed autosave option

**Review by fewtarius — APPROVED** [review]
This looks great, thanks!  @brooksytech would you mind taking a look as well before we merge?

**Comment by asoderq** [comment]
Oh and ST-V should be supported by the Saturn core, but I didn't test it. It at least would need to be enabled in virtual/emulators/package.mk

But I won't open that potentiall can of worms now, as I rather merge it.

**Comment by brooksytech** [comment]
Yep, ill take a look later today.

**Comment by asoderq** [comment]
I have noticed that my core option parsing strategy isn't great, as I get bash syntax errors when they are set to default, but it somehow works anyway. If someone more experiences has an idea of to handle the the ES core options propagate them to command line switches i would be super happy. I have on purpose name the options exactly like the command line switches, but I still manually check all options with if statements in start_mednafen.sh

**Comment by asoderq** [comment]
Here is the controls docs that goes with it: https://github.com/asoderq/jelos.org/blob/mednafen_controls/docs/play/controls.md#mednafen-hotkeys

**Comment by brooksytech** [comment]
Looks good to me. Will go ahead and merge.

**Pull request merged**
