### PR TITLE
Add WireGuard support with wg-quick

### PR DESCRIPTION
**Pull request by kkoshelev**
# Add WireGuard support with wg-quick

## Description

This adds WireGuard VPN support for the firmware. The changes include:
* Enable WireGuard kernel and user components using OS options
* Add missing wg-quick script to the list of included files
* Changes to busybox component to support missing features used by wg-quick
** stat now support "-c" option
** "ip rule" now supports "not" keyword.
** "ip" command now supports arbitrary numeric routing tables above 1024.
** iproute2 tables folder now porints to writable location

Fixes # (issue)

## Type of change

Please delete options that are not relevant.
- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested Locally?

The firmware was compiled and installed on RG351V device. The following VPN client configuration file was used.
--- wg1.conf ---
[Interface]
PrivateKey = reducted
Address = 10.17.10.12/24

[Peer]
PublicKey = reducted
AllowedIPs = 0.0.0.0/0
Endpoint = reducted
---

The following commands were run to verify that connectivity is established succesfully.

 $ curl ifconfig.co -4
my local wan ip reducted

$ wg-quick up ./wg1.conf
Warning: `/storage/wg1.conf' is world accessible
[#] ip link add wg1 type wireguard
[#] wg setconf wg1 /dev/fd/63
[#] ip -4 address add 10.17.10.12/24 dev wg1
[#] ip link set mtu 1420 up dev wg1
[#] wg set wg1 fwmark 51820
[#] ip -4 route add 0.0.0.0/0 dev wg1 table 51820
[#] ip -4 rule add not fwmark 51820 table 51820
[#] ip -4 rule add table main suppress_prefixlength 0
[#] sysctl -q net.ipv4.conf.all.src_valid_mark=1
[#] iptables-restore -n

Precompiled iperf3 was copied over.

$ ./iperf3 -c 10.17.10.1 -t 30
Connecting to host 10.17.10.1, port 5201
[  5] local 10.17.10.12 port 32920 connected to 10.17.10.1 port 5201
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[....]
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-30.00  sec  58.8 MBytes  16.4 Mbits/sec   18             sender
[  5]   0.00-30.17  sec  56.8 MBytes  15.8 Mbits/sec                  receiver

iperf Done.

During performance testing the CPU cores load was the following (20%, 5%, 5%, 5%).

Very the ip address 
 $ curl ifconfig.co -4
ip of VPN server

$ wg-quick down ./wg1.conf
Warning: `/storage/wg1.conf' is world accessible
[#] ip -4 rule delete table 51820
[#] ip -4 rule delete table main suppress_prefixlength 0
[#] ip link delete dev wg1
[#] iptables-restore -n

**Test Configuration**: RG351V
* Build OS name and version: custom built FW dev branch
* Docker (Y/N): N
* JELOS Branch: dev
* Any additional information that may be useful:* 

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

Note: This PR template is adapted from [embeddedartistry](https://github.com/embeddedartistry/templates/blob/master/oss_docs/PULL_REQUEST_TEMPLATE.md)

### CODE REVIEW

**Review by fewtarius — COMMENTED** [review]
This looks good, thanks for the PR!  The only change I can see from a glance is that $INSTALL should be braced for consistency in the busy box package, which isn't significant.  I don't have a mechanism to test this, but I'll pull the PR and do a test build before approving.

I'd recommend joining our discord if you're not a member already as we may have some questions after building.

**Review by fewtarius — COMMENTED** [review]
It looks like there is an issue building it that will need to be worked through, wireguard-linux-compat seems to be pretty out of date and it's erroring out.  Updating the package may correct it.

**Comment by kkoshelev** [comment]
I just sent you a few messages on Discord with details, etc. I don't have issues building, at least for the platform I use (RG351V).

**Comment by kkoshelev** [comment]
Loaded RG351V FW with updated version of kernel mod, run the same tests, got similar results. Everything works as expected.

**Pull request merged**
